# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['../main.py'],
    pathex=['..', '../diagnostico'],
    binaries=[],
    datas=[
        ('../bancos.json',                   '.'),
        ('../sap_gui.py',                    '.'),
        ('../transactions/__init__.py',      'transactions'),
        ('../transactions/zfiec015_kb.py',   'transactions'),
        ('../transactions/fb60_kb.py',       'transactions'),
        ('../correos/__init__.py',           'correos'),
        ('../correos/notificador_sap.py',    'correos'),
        ('../correos/outlook_notifier.py',   'correos'),
        ('../diagnostico/campos.py',         'diagnostico'),
    ],
    hiddenimports=[
        'win32com.client',
        'win32com.shell',
        'win32com.shell.shell',
        'win32api',
        'win32gui',
        'win32con',
        'win32process',
        'pynput.keyboard._win32',
        'pynput.mouse._win32',
        'pyautogui',
        'pyperclip',
        'dotenv',
        'msal',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['imagenes'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ComBancos',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
    onefile=True,
)
